# Generated by Django 3.1.4 on 2020-12-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player1',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='player2',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
