# Generated by Django 3.1.4 on 2020-12-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20201212_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
