# Generated by Django 3.1.4 on 2020-12-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_room_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player2',
        ),
    ]
