# Generated by Django 3.1.4 on 2020-12-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20201215_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room',
            new_name='room_model',
        ),
    ]
