# Generated by Django 3.1.4 on 2020-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_room_model_no_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_model',
            name='re',
            field=models.IntegerField(default=0),
        ),
    ]
